version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - shared-network

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - shared-network

networks:
  shared-network:

volumes:
  mongodb_data_container:
